### ISSUE TITLE
Build error on latest dev-v2 branch

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#162]
content is served from ./dist/
 40% 1/2 build modulesTypeError: Cannot read property 'visitClass' of undefined
    at monkeypatch (/home/cjh/work/source/hpccloud/node_modules/babel-eslint/index.js:220:40)
    at Object.exports.parse (/home/cjh/work/source/hpccloud/node_modules/babel-eslint/index.js:362:5)
    at parse (/home/cjh/work/source/hpccloud/node_modules/eslint/lib/eslint.js:512:27)
    at EventEmitter.module.exports.api.verify (/home/cjh/work/source/hpccloud/node_modules/eslint/lib/eslint.js:646:19)
    at processText (/home/cjh/work/source/hpccloud/node_modules/eslint/lib/cli-engine.js:230:27)
    at CLIEngine.executeOnText (/home/cjh/work/source/hpccloud/node_modules/eslint/lib/cli-engine.js:686:26)
    at lint (/home/cjh/work/source/hpccloud/node_modules/eslint-loader/index.js:25:20)
    at Object.module.exports (/home/cjh/work/source/hpccloud/node_modules/eslint-loader/index.js:112:3)
    at WEBPACK_CORE_LOADER_EXECUTION (/home/cjh/work/source/hpccloud/node_modules/webpack-core/lib/NormalModuleMixin.js:155:71)
    at runSyncOrAsync (/home/cjh/work/source/hpccloud/node_modules/webpack-core/lib/NormalModuleMixin.js:155:93)

npm ERR! Linux 3.13.0-74-generic
npm ERR! argv "/home/cjh/.nvm/versions/node/v5.4.1/bin/node" "/home/cjh/.nvm/versions/node/v5.4.1/bin/npm" "start"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! hpc-cloud@0.0.0-semantically-release start: `webpack-dev-server --progress --open`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hpc-cloud@0.0.0-semantically-release start script 'webpack-dev-server --progress --open'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the hpc-cloud package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --progress --open
npm ERR! You can get their info via:
npm ERR!     npm owner ls hpc-cloud
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cjh/work/source/hpccloud/npm-debug.log
(cumulus)cjh@ulex:~/work/source/hpccloud dev-v2$

**Comment by cjh1** [comment]
@jourdain @TristanWright I am seeing the above error on our dev branch.

**Comment by jourdain** [comment]
You can fix that by changing the version of "babel-eslint" to either 4.1.8 or 5.0.0-beta10.

**Comment by cjh1** [comment]
Can we push a fix for it?

**Comment by jourdain** [comment]
It is on its way but I just got here...

**Comment by cjh1** [comment]
Sure, no rush
