### ISSUE TITLE
are file extensions required or should there be a default?

### ISSUE THREAD

**Issue by TristanWright** [Kitware/HPCCloud#201]
When running PyFr we get the log: 

```
[13:42:42.870] INFO: Downloading input mesh.
[13:42:42.870] INFO: Downloading complete.
[13:42:42.870] ERROR: Exception raise by task: list index out of range
```

A more precise error in `command.log` leading to [this line](https://github.com/Kitware/HPCCloud/blob/dev-v2/server/taskflows/hpccloud/taskflow/pyfr.py#L159)
```
[2016-03-02 23:54:30,136: ERROR/Worker-3] Exception raise by task: list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "cumulus/taskflow/__init__.py", line 118, in wrapped
    return func(celery_task, *args, **kwargs)
  File "/opt/hpccloud/hpccloud/server/taskflows/hpccloud/taskflow/pyfr.py", line 159, in import_mesh
    extn = file['exts'][0]
IndexError: list index out of range
[2016-03-02 23:54:30,182: ERROR/MainProcess] Task hpccloud.taskflow.pyfr.import_mesh[f276c2b0-f20f-4b39-85c9-e1be1ac8a111] raised unexpected: IndexError('list index out of range',)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "cumulus/taskflow/__init__.py", line 118, in wrapped
    return func(celery_task, *args, **kwargs)
  File "/opt/hpccloud/hpccloud/server/taskflows/hpccloud/taskflow/pyfr.py", line 159, in import_mesh
    extn = file['exts'][0]
IndexError: list index out of range
```

Fetching the file from the API however `exts` has no content:

![screen shot 2016-03-02 at 17 12 59](https://cloud.githubusercontent.com/assets/13318121/13480300/1b6be752-e09a-11e5-9e4b-0dce656049e0.png)

**Comment by cjh1** [comment]
A file extension is required at the moment as that is how we ( PyFR )
determines the mesh type

**Comment by TristanWright** [comment]
got this sorted out in 81ee5a9ef887807430ead9ee5ee4ad26ad37c5a4, thanks.
