### ISSUE TITLE
pyfr errors out in DEMO mode

### ISSUE THREAD

**Issue by chetnieter** [Kitware/HPCCloud#521]
Now that the backend issue has been resolved I am seeing errors on the next step. From the celery logs. I see a mix of python3.4 and python2.7. Could that be the issue?

[2016-09-15 19:53:32,887: ERROR/Worker-3] Traceback (most recent call last):
  File "/usr/local/bin/pyfr", line 9, in <module>
    load_entry_point('pyfr==1.3.0', 'console_scripts', 'pyfr')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python3.4/dist-packages/pyfr/scripts/main.py", line 11, in <module>
    import h5py
  File "/usr/local/lib/python3.4/dist-packages/h5py/__init__.py", line 34, in <module>
    from ._conv import register_converters as _register_converters
  File "h5t.pxd", line 14, in init h5py._conv (/tmp/pip_build_root/h5py/h5py/_conv.c:6880)
  File "numpy.pxd", line 66, in init h5py.h5t (/tmp/pip_build_root/h5py/h5py/h5t.c:19113)
  File "/usr/local/lib/python3.4/dist-packages/numpy/__init__.py", line 153, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python3.4/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python3.4/dist-packages/numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "/usr/local/lib/python3.4/dist-packages/numpy/lib/polynomial.py", line 19, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/usr/local/lib/python3.4/dist-packages/numpy/linalg/__init__.py", line 50, in <module>
    from .linalg import *
  File "/usr/local/lib/python3.4/dist-packages/numpy/linalg/linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: /usr/local/lib/python3.4/dist-packages/numpy/linalg/lapack_lite.cpython-34m.so: undefined symbol: dpotrf_
Traceback (most recent call last):
  File "/opt/hpccloud/hpccloud/server/taskflows/hpccloud/taskflow/pyfr.py", line 146, in _import_mesh
    subprocess.check_output(command, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['pyfr', 'import', '-t', 'gmsh', '/tmp/tmpS3DAkb', u'/tmp/tmpofQLHn/euler_vortex_2d.pyfrm']' returned non-zero exit status 1
[2016-09-15 19:53:32,926: INFO/Worker-3] Starting new HTTP connection (1): dune.kitware.com
[2016-09-15 19:53:32,940: INFO/Worker-3] Starting new HTTP connection (1): dune.kitware.com
[2016-09-15 19:53:32,958: INFO/Worker-3] Starting new HTTP connection (1): dune.kitware.com
[2016-09-15 19:53:32,957: ERROR/Worker-3] Exception raise by task.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/hpccloud/cumulus/cumulus/taskflow/__init__.py", line 117, in wrapped
    return func(celery_task, *args, **kwargs)
  File "/opt/hpccloud/hpccloud/server/taskflows/hpccloud/taskflow/pyfr.py", line 281, in setup_input
    _import_mesh(task.taskflow.logger, input_path, output_path, extn)
  File "/opt/hpccloud/hpccloud/server/taskflows/hpccloud/taskflow/pyfr.py", line 146, in _import_mesh
    subprocess.check_output(command, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['pyfr', 'import', '-t', 'gmsh', '/tmp/tmpS3DAkb', u'/tmp/tmpofQLHn/euler_vortex_2d.pyfrm']' returned non-zero exit status 1
[2016-09-15 19:53:32,974: ERROR/MainProcess] Task hpccloud.taskflow.pyfr.setup_input[f694e09c-9734-4b80-ba14-8c9823e7e5fd] raised unexpected: CalledProcessError()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/hpccloud/cumulus/cumulus/taskflow/__init__.py", line 117, in wrapped
    return func(celery_task, *args, **kwargs)
  File "/opt/hpccloud/hpccloud/server/taskflows/hpccloud/taskflow/pyfr.py", line 281, in setup_input
    _import_mesh(task.taskflow.logger, input_path, output_path, extn)
  File "/opt/hpccloud/hpccloud/server/taskflows/hpccloud/taskflow/pyfr.py", line 146, in _import_mesh
    subprocess.check_output(command, stderr=subprocess.STDOUT)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError

**Comment by cjh1** [comment]
Looks like there is a missing symbol:

```
ImportError: /usr/local/lib/python3.4/dist-packages/numpy/linalg/lapack_lite.cpython-34m.so: undefined symbol: dpotrf
```

Inside your VM try running pyfr directly and see if get the same error. Not sure if we are installing pyfr master, but something may have changed upstream.

**Comment by cjh1** [comment]
I looked at out PyFR role and we are install v1.3, so nothing would have changed with PyFR, I am trying on my machine now.

**Comment by chetnieter** [comment]
Could this be an issue with libblas vs libopenblas? I noticed that on the DEMO VM in mongo for the pyfr backend in the cluster config we have.

`"openmp" : [
				{
					"cblas" : "/usr/lib/libblas.so",
					"name" : "demo_profile"
				}
			]`

But on my VM I am using for development the config for ulmus is.

`"openmp" : [
				{
					"cc" : "",
					"cblas-type" : "",
					"cblas" : "/usr/lib/openblas-base/libblas.so.3",
					"name" : "Default",
					"cflags" : ""
				}
			],`

I checked and it looks like the openblas libraries are on the demo VM.

**Comment by cjh1** [comment]
I tried running pyfr manually on my demo VM and it runs fine. /usr/lib/libblas.so exists. Can you look on your VM at the job that failed and looking at the input file to check tha the cblas property is being set, its possible that it not being sent to the taskflow by the client.

**Comment by cjh1** [comment]
When I first try to run a simulation on the demo cluster the back-end dropdown is not populated, I thought that was fixed? I am using v0.9-rc1.

**Comment by chetnieter** [comment]
It was fixed in #519 which was merged in release early yesterday. I tested against the branch itself since it wasn't merged at the time. Is v0.9-rc1 installing the release branch of hpccloud?

**Comment by cjh1** [comment]
v0.9-rc1 is installing v0.9-rc1 for cumulus and hpccloud, that is probably the difference in our environments, I will try the release branch.

**Comment by chetnieter** [comment]
So is this what I am looking for?

`[backend-openmp]`
`cblas = /usr/lib/libblas/libblas.so`

If that is the case then it is missing from the input file that I pulled off of girder whose id matches the one in the taskflow request. I am little confused because the error seems to be coming from the following command:

`pyfr import -t gmsh /tmp/tmpMknFt8 /tmp/tmp5vgnS_/euler_vortex_2d.pyfrm`

Which isn't using the input file.

**Comment by cjh1** [comment]
Ok, its coming from the mesh import, can you run that command manually in the VM, does it fail?

**Comment by chetnieter** [comment]
Yes - I gives the same import error we see in the log.

`ImportError: /usr/local/lib/python3.4/dist-packages/numpy/linalg/lapack_lite.cpython-34m.so: undefined symbol: dpotrf_`

**Comment by cjh1** [comment]
Can run run ldd /usr/local/lib/python3.4/dist-packages/numpy/linalg/lapack_lite.cpython-34m.so

**Comment by chetnieter** [comment]
`vagrant@vagrant-ubuntu-trusty-64:~$ ldd /usr/local/lib/python3.4/dist-packages/numpy/linalg/lapack_lite.cpython-34m.so`
`	linux-vdso.so.1 =>  (0x00007ffda3dfc000)`
`	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f436b25a000)`
`	/lib64/ld-linux-x86-64.so.2 (0x00007f436b826000)`

**Comment by chetnieter** [comment]
On a lark I tried changed the BLAS library for the demo_cluster to `/usr/lib/openblas-base/libblas.so.3` but I get the same error.

**Comment by cjh1** [comment]
Can you check your numpy version:

```
>>> import numpy
>>> print numpy.__version__
1
```

**Comment by chetnieter** [comment]
```
vagrant@vagrant-ubuntu-trusty-64:/var/log/celery$ python3
Python 3.4.3 (default, Oct 14 2015, 20:28:29)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'1.11.0'
```

**Comment by chetnieter** [comment]
So I messed with the ansible pyfr provisioning and dropped it from version 1.3 to 1.2 since I noticed 1.2 was installed on ulmus. It appears to get past the mesh importing but is now failing to get the input file id.

```
[2016-09-16 17:03:20,948: INFO/Worker-2] Uploading converted mesh.
[2016-09-16 17:03:20,960: INFO/Worker-2] Starting new HTTP connection (1): Dune-4653.local
[2016-09-16 17:03:20,977: INFO/Worker-2] Starting new HTTP connection (1): Dune-4653.local
[2016-09-16 17:03:21,003: INFO/Worker-2] Starting new HTTP connection (1): Dune-4653.local
[2016-09-16 17:03:20,999: INFO/Worker-2] Upload input complete.
[2016-09-16 17:03:21,014: INFO/Worker-2] Starting new HTTP connection (1): Dune-4653.local
[2016-09-16 17:03:21,012: INFO/Worker-2] Updating backend configuration.
[2016-09-16 17:03:21,055: INFO/Worker-2] Starting new HTTP connection (1): Dune-4653.local
[2016-09-16 17:03:21,075: INFO/Worker-2] Starting new HTTP connection (1): Dune-4653.local
[2016-09-16 17:03:21,091: INFO/Worker-2] Starting new HTTP connection (1): Dune-4653.local
[2016-09-16 17:03:21,090: ERROR/Worker-2] Exception raise by task.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/hpccloud/cumulus/cumulus/taskflow/__init__.py", line 117, in wrapped
    return func(celery_task, *args, **kwargs)
  File "/opt/hpccloud/hpccloud/server/taskflows/hpccloud/taskflow/pyfr.py", line 348, in setup_input
    update_config_file(task, client, *args, **kwargs)
  File "/opt/hpccloud/hpccloud/server/taskflows/hpccloud/taskflow/pyfr.py", line 183, in update_config_file
    ini_file_id = kwargs['input']['iniFile']['id']
KeyError: 'id'```

**Comment by cjh1** [comment]
@TristanWright No?

**Comment by TristanWright** [comment]
Did any of these errors show up in the console? 

https://github.com/Kitware/HPCCloud/blob/master/src/workflows/pyfr/pyfr-simput/components/steps/Input/index.js#L135-L160

**Comment by chetnieter** [comment]
This is working now with the changes introduced in the v0.9-rc2 tag.
