### ISSUE TITLE
gulp serve throws an error

### ISSUE THREAD

**Issue by cjh1** [Kitware/HPCCloud#9]
@TristanWright Did we every resolve this issue?

[12:18:50] 'watch' errored after 196 ms
[12:18:50] TypeError: Cannot read property 'prototype' of undefined
    at Object.exports.inherits (util.js:556:43)
    at Object.<anonymous> (/home/cjh/work/source/HPCCloud/node_modules/browser-sync/node_modules/http-proxy/lib/http-proxy/index.js:111:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/cjh/work/source/HPCCloud/node_modules/browser-sync/node_modules/http-proxy/lib/http-proxy.js:4:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/cjh/work/source/HPCCloud/node_modules/browser-sync/node_modules/http-proxy/index.js:13:18)

**Comment by TristanWright** [comment]
For now I'm getting around this right now by using a watch task that doesn't invoke browser-sync and instead running `python -m SimpleHTTPServer 3000` in the `dist/` folder.
